[package]
name = "nowork"
version = "0.0.7"
description = "nowork desktop shell"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools", "tray-icon"] }
rfd = "0.15"
dunce = "1"  # Simplify Windows UNC paths (\\?\) to regular DOS paths
tauri-plugin-notification = "2.3.3"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
